services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - inception:/var/www
      - ./requirements/nginx/conf/default.conf:/etc/nginx/http.d/default.conf
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    # depends_on:
      # - mariadb
    networks:
      - inception
    volumes:
      - inception:/var/www
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    args:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_ROOT: ${DB_ROOT}
    networks:
      - inception
    # volumes:
    #   - db:
    ports:
      - 3306:3306
    restart: always

volumes:
  inception:
    driver: local
    driver_opts:
      type: none
      device: ~/guferrei/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ~/guferrei/data/db
      o: bind

networks:
  inception:
    driver: bridge